### ISSUE TITLE
Add "Exists in Jamf" checkboxes

### ISSUE THREAD

**Issue by JustATechie** [USS-IT/SnipeITWinSync#8]

**Comment by mcarras8** [comment]
@JustATechie 
Just to note, checkboxes in Snipe-It are actually a string field delimited with a comma and a space, where the order of the fields matter. E.g., "Exists in JAMF, Verified" is different than "Verified, Exists in JAMF" (the PowerShell sync script assumes the checkboxes are sorted alphanumeric). So adding this to the Python script wouldn't exactly be trivial.

I think an easier way to verify if something is in JAMF may be to either sync the jamfid to a new custom field, or the last date of a successful sync. If we do the latter then we wouldn't need to worry about reading all Apple devices from Snipe-It to check if they still exist in JAMF.

**Comment by mcarras8** [comment]
@JustATechie 
Today we encountered an issue with a Macbook that had the default name "Macbook Air" in JAMF, and for some reason while the S/N was searchable in Snipe-It we couldn't search it in JAMF. Because of this, I think syncing the jamf-id in a custom field might be a good idea rather than trying to sync an "Exists in JAMF" checkbox. We could probably get rid of the "Exists in AirWatch" checkbox too, don't think it's needed.

What do you think?
